CREATE TABLE `t_batch_mst` (
  `TBM_ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `TBM_LAST_RUN_TS` datetime DEFAULT NULL,
  `TBM_STATUS` char(1) DEFAULT NULL,
  PRIMARY KEY (`TBM_ID`)
);

 CREATE TABLE `t_fbmsg_tracker_mst` (
  `TFTM_ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `TFTM_CONV_ID` varchar(50) DEFAULT NULL,
  `TFTM_MSG_ID` varchar(50) DEFAULT NULL,
  `TFTM_FROM_ID` varchar(50) DEFAULT NULL,
  `TFTM_TO_ID` varchar(50) DEFAULT NULL,
  `TFTM_FROM_NAME` varchar(100) DEFAULT NULL,
  `TFTM_TO_NAME` varchar(100) DEFAULT NULL,
  `TFTM_CREATED_TS` datetime DEFAULT NULL,
  PRIMARY KEY (`TFTM_ID`)
);

CREATE TABLE `t_prediction_log_mst` (
  `TPLM_ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `TPLM_CONV_ID` varchar(50) DEFAULT NULL,
  `TPLM_MSG` varchar(200) DEFAULT NULL,
  `TPLM_TYPE` varchar(1) DEFAULT NULL,
  `TPLM_LABEL` varchar(50) DEFAULT NULL,
  `TPLM_CREATED_TS` datetime DEFAULT NULL,
  `TPLM_MSG_SENTIMENT_MAGN` varchar(5) DEFAULT NULL,
  `TPLM_MSG_SENTIMENT_POLARITY` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TPLM_ID`)
);

CREATE TABLE `t_processing_log_mst` (
  `TAPLM_ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `TAPLM_CONV_ID` varchar(50) DEFAULT NULL,
  `TAPLM_FROM_ID` varchar(50) DEFAULT NULL,
  `TAPLM_CURR_INSTRUCTION` varchar(1) DEFAULT NULL,
  `TAPLM_EXPT_INSTRUCTION` varchar(1) DEFAULT NULL,
  `TAPLM_TRNS_IND` varchar(10) DEFAULT NULL,
  `TAPLM_MSG` varchar(200) DEFAULT NULL,
  `TAPLM_PROCESS_IND` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`TAPLM_ID`)
);

